services:
  - type: web
    name: webx-command-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: PORT
        value: 10000
